# Generated by Django 4.0.6 on 2022-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_meal_directions_remove_meal_ingnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='lists',
            field=models.ManyToManyField(to='main_app.list'),
        ),
    ]
