# Generated by Django 4.0.6 on 2022-07-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_day_meal_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='week',
            new_name='day',
        ),
    ]
