# Generated by Django 4.0.6 on 2022-07-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_meal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
    ]
