# Generated by Django 4.0.6 on 2022-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_meal_options_remove_recipe_chowtime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='chowtime',
        ),
        migrations.AddField(
            model_name='recipe',
            name='chowtime',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
