# Generated by Django 4.0.6 on 2022-07-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_meal_options_remove_meal_chowtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='chowtime',
        ),
    ]
